### ISSUE TITLE
Dashboard tab is not working when NODE_PORTWS has been overriden

### ISSUE THREAD

**Issue by stephenjannin** [devfacet/natsboard#1]
When overriding NODE_PORTWS on the command line, the client part is still trying to connect on NODE_PORT+1.

**Comment by devfacet** [comment]
The UI (client side) should fetch that information from the server. Easiest solution is defining a new route (i.e. `/config`) in https://github.com/fatihcode/natsboard/blob/master/lib/routes.js and return config information for the UI.

I will look at it when I have chance. Meanwhile PRs are welcome :)

**Comment by devfacet** [comment]
Fixed by #14
