### ISSUE TITLE
Connections tab : Client description could be more accurate

### ISSUE THREAD

**Issue by stephenjannin** [devfacet/natsboard#3]
In app.js, you could replace 
content += '<td>' + val.lang + ' / ' + val.version + '</td>';
by
content += '<td>' + val.name + '</td>';

This could give a better client description with the name give on the client side.

**Comment by devfacet** [comment]
@stephenjannin : `name` is optional and default is empty. ( https://github.com/nats-io/gnatsd/blob/master/server/monitor.go#L52 )

How this looks like to you;

``` javascript
content += '<td>' + (val.name ? val.name + ' (' + val.lang + '/' + val.version + ')' : val.lang + '/' + val.version) + '</td>';
```
