### ISSUE TITLE
Don't see connections in "connections" tab

### ISSUE THREAD

**Issue by Hronom** [devfacet/natsboard#6]
I have two apps: message generator and consumer. 
I run this apps and don't see any connections in `connections` tab, but on `dashboard` tab I see two connections, messages tik and all other stuff. When I shutdown message generator the consumer appears on `connections` tab.

**Comment by devfacet** [comment]
@Hronom : Can you try natsboard@4.0.2 ? ( PR #7 may fix your issue )

**Comment by Hronom** [comment]
@fatihcode In natsboard@4.0.2 problem solved
